version: "2"
services:
  solar_maker:
    build:
      context: .
      dockerfile: ./devops/Dockerfile.local
    ports:
      - 80:8000
    volumes:
      - ./:/var/www/html
    networks:
      - solar_maker
    tty: true
    container_name: solar_maker
  mysql_solar_maker:
    image: mariadb:10.3
    entrypoint: docker-entrypoint.sh --sql-mode='STRICT_TRANS_TABLES,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    ports:
      - 3306:3306
    networks:
      - solar_maker
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=solar_maker
    container_name: mysql_solar_maker
  phpmyadmin_solar_maker:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    networks:
      - solar_maker
    environment:
      PMA_HOST: mysql_solar_maker
    container_name: phpmyadmin_solar_maker
networks:
  solar_maker:
    external:
      name: solar_maker_network
